# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle
# 

Name:       rsc-c
Summary:    Cross-platform RuneScape Classic source port
Version:    0.1.0
Release:    1
Group:      Applications/Games
License:    AGPL-3.0-or-later
URL:        https://github.com/2003scape/rsc-c
Source0:    %{name}-%{version}.tar.bz2

BuildRequires: gcc
BuildRequires: make
BuildRequires: pkgconfig(sdl2)
BuildRequires: pkgconfig(SDL2_image)
BuildRequires: pkgconfig(maliit-glib)
BuildRequires: pkgconfig(glib-2.0)
BuildRequires: pkgconfig(gio-2.0)

Requires: SDL2
Requires: SDL2_image
Requires: maliit-framework-wayland-glib

%description
Cross-platform open source RuneScape Classic client.

%prep
%setup -q

%build
# >> build pre
export SAILFISH=1
export PREFIX=%{_prefix}
if [ ! -f Makefile ]; then
    echo "Top-level Makefile not found"
    exit 1
fi
# << build pre

if [ "${CLEAN_BUILD:-0}" = "1" ]; then
    make clean
fi

make %{?_smp_mflags} SDL2=1 RENDER_GL=1 LEGACY_GL=1 GLAD=1

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
export SAILFISH=1
export PREFIX=%{_prefix}
if [ ! -f Makefile ]; then
    echo "Top-level Makefile not found"
    exit 1
fi
# << install pre

make install DESTDIR=%{buildroot} SDL2=1 RENDER_GL=1 LEGACY_GL=1 GLAD=1

# Replace generic desktop/icon installs with Sailfish paths.
rm -f %{buildroot}%{_datadir}/applications/*.desktop
rm -f %{buildroot}%{_datadir}/pixmaps/rsc-c.png
install -d %{buildroot}%{_datadir}/applications
install -d %{buildroot}%{_datadir}/icons/hicolor/86x86/apps
install -m 644 freedesktop/rsc-c.desktop \
    %{buildroot}%{_datadir}/applications/harbour-rsc-c.desktop
install -m 644 web/icon.png \
    %{buildroot}%{_datadir}/icons/hicolor/86x86/apps/harbour-rsc-c.png

# Sailfish wrapper entrypoint.
install -m 755 sailfish/harbour-rsc-c.sh %{buildroot}%{_bindir}/harbour-rsc-c

# >> install post
# << install post

%files
%license COPYING
%doc README.md README-SDL.txt
%{_bindir}/mudclient
%{_bindir}/harbour-rsc-c
%{_datadir}/rsc-c
%{_datadir}/applications/harbour-rsc-c.desktop
%{_datadir}/icons/hicolor/86x86/apps/harbour-rsc-c.png

%changelog
